captainVersion: 4
services:
    $$cap_appname-mysql:
        volumes:
            - $$cap_appname-mysql-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: leantime
            MYSQL_ROOT_PASSWORD: $$cap_mysql_passwd
            MYSQL_USER: leantimeuser
            MYSQL_PASSWORD: $$cap_mysql_passwd
        caproverExtra:
            dockerfileLines:
                - FROM mysql:8.0.32
                - CMD ["--character-set-server=UTF8MB4", "--collation-server=UTF8MB4_unicode_ci"]
    $$cap_appname:
        image: elestio/leantime:$$cap_leantime_ver
        container_name: leantime
        environment:
            LEAN_APP_URL: https://$$cap_appname.$$cap_root_domain
            LEAN_DB_HOST: srv-captain--$$cap_appname-mysql
            LEAN_DB_USER: leantimeuser
            LEAN_DB_PASSWORD: $$cap_mysql_passwd
            LEAN_DB_DATABASE: leantime
            LEAN_DEFAULT_TIMEZONE: $$cap_timezone
            LEAN_SESSION_PASSWORD: $$cap_gen_random_hex(32)
            LEAN_SESSION_EXPIRATION: 28800
        volumes:
            - $$cap_appname-public-userfiles:/var/www/html/public/userfiles
            - $$cap_appname-userfiles:/var/www/html/userfiles
caproverOneClickApp:
    variables:
        - id: $$cap_mysql_passwd
          label: MySQL User Password
          description: User password for the database instance.
          defaultValue: $$cap_gen_random_hex(16)
          validRegex: /^(?=.*\d).{10,}$/
        - id: $$cap_leantime_ver
          label: Leantime Version (from elestio/leantime)
          description: 'Check out their Docker page for valid tags https://hub.docker.com/r/elestio/leantime'
          defaultValue: latest
          validRegex: /.+/
        - id: $$cap_timezone
          label: Timezone
          description: This is the timezone for the application, find yours at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
          defaultValue: Europe/London
    instructions:
        start: |-
            Leantime is an open source project management system for small teams and startups. This deployment uses the **elestio/leantime** image with additional storage for user files.
        end: |-
            ✅  Leantime has been successfully deployed and will soon be available at https://$$cap_appname.$$cap_root_domain!

            ❗️ **IMPORTANT**: Before accessing the Leantime dashboard, you must enable HTTPS:

            **Step 1**: Go to the settings for `$$cap_appname`
            **Step 2**: Enable **HTTPS**

            --------------------------------------------
            🔰 More information on initial configuration can be found at https://docs.leantime.io/#/.
    displayName: Leantime (elestio)
    isOfficial: false
    description: Leantime is an open source project management system for small teams and startups. This version uses the elestio image with persistent user file storage.
    documentation: More information on initial configuration can be found at https://docs.leantime.io/#/. Based on the elestio Docker Compose at https://hub.docker.com/r/elestio/leantime.
