captainVersion: 4
caproverOneClickApp:
    instructions:
        start: |-
            Deploying Solidus: A free, open-source e-commerce platform built with Ruby on Rails.
            Solidus gives you complete control over your store with a flexible, modular architecture.
            **Included Components:**
            - Solidus e-commerce platform
            - SQLite database (built-in, no external database needed)
            **Note:** The database is automatically set up on first start. No configuration needed!
        end: |-
            Done! 🎉
            Your Solidus e-commerce store is now deployed and ready to use.
            **Access Your Store:**
            - Storefront: https://$$cap_appname.$$cap_root_domain
            - Admin Panel: https://$$cap_appname.$$cap_root_domain/admin
            See https://guides.solidus.io/ for documentation and customization guides.
    displayName: Solidus (SQLite)
    isOfficial: false
    description: Free, open-source e-commerce platform built with Ruby on Rails. Complete control over your store with flexible, modular architecture. Uses SQLite for simplicity - no external database required.

    variables:
        - id: $$cap_solidus_image
          label: Solidus Image
          defaultValue: 'solidus-demo:latest'
          description: Docker image name for Solidu
          validRegex: /^.+$/
        - id: $$cap_admin_email
          label: Admin Email
          defaultValue: admin@example.com
          description: Email address for the admin user
          validRegex: /^[^\s@]+@[^\s@]+\.[^\s@]+$/
        - id: $$cap_admin_password
          label: Admin Password
          defaultValue: $$cap_gen_random_hex(12)
          description: Password for the admin user (auto-generated)
          validRegex: /.{8,}/
        - id: $$cap_secret_key_base
          label: Secret Key Base
          defaultValue: $$cap_gen_random_hex(64)
          description: Rails secret key base for encryption (auto-generated)
          validRegex: /.{32,}/
        - id: $$cap_load_sample_data
          label: Load Sample Data
          defaultValue: 'true'
          description: Load sample products and data (true/false)
          validRegex: /^(true|false)$/

services:
    $$cap_appname:
        image: $$cap_solidus_image
        restart: always
        environment:
            RAILS_ENV: production
            ADMIN_EMAIL: $$cap_admin_email
            ADMIN_PASSWORD: $$cap_admin_password
            SECRET_KEY_BASE: $$cap_secret_key_base
            LOAD_SAMPLE_DATA: $$cap_load_sample_data
            RAILS_LOG_TO_STDOUT: 'true'
            RAILS_SERVE_STATIC_FILES: 'true'
        caproverExtra:
            containerHttpPort: '3000'
            websocketSupport: 'true'
        volumes:
            - $$cap_appname-data:/rails/public/system
            - $$cap_appname-storage:/rails/storage
