captainVersion: 4
caproverOneClickApp:
    instructions:
        start: |-
            Deploying Solidus: A free, open-source e-commerce platform built with Ruby on Rails.
            Solidus gives you complete control over your store with a flexible, modular architecture.

            **Included Components:**
            - Solidus e-commerce platform
            - SQLite database (built-in, no external database needed)
            **Note:** The database is automatically set up on first start. No configuration needed!
        end: |-
            Done! 🎉
            Your Solidus e-commerce store is now deployed and ready to use.
            **Access Your Store:**
            - Storefront: https://$$cap_appname.$$cap_root_domain
            - Admin Panel: https://$$cap_appname.$$cap_root_domain/admin

            **Default Admin Credentials:**
            - Email: $$cap_admin_email
            - Password: $$cap_admin_password

            See https://guides.solidus.io/ for documentation and customization guides.
    displayName: Solidus (SQLite)
    isOfficial: false
    description: Free, open-source e-commerce platform built with Ruby on Rails. Complete control over your store with flexible, modular architecture. Uses SQLite for simplicity - no external database required.

    variables:
        - id: $$cap_solidus_image
          label: Solidus Image
          defaultValue: 'solidus-demo:latest'
          description: Docker image name for Solidus
          validRegex: /^.+$/
        - id: $$cap_rails_env
          label: Rails Environment
          defaultValue: 'development'
          description: Rails environment (development, production, test)
          validRegex: /^(development|production|test)$/
        - id: $$cap_secret_key_base
          label: Secret Key Base
          defaultValue: $$cap_gen_random_hex(64)
          description: Rails secret key for encryption (auto-generated)
          validRegex: /.{1,}/
        - id: $$cap_admin_email
          label: Admin Email
          defaultValue: 'admin@example.com'
          description: Email address for the initial admin user
          validRegex: /^[^\s@]+@[^\s@]+\.[^\s@]+$/
        - id: $$cap_admin_password
          label: Admin Password
          defaultValue: $$cap_gen_random_hex(16)
          description: Password for the initial admin user (auto-generated)
          validRegex: /.{8,}/
        - id: $$cap_rails_log_level
          label: Rails Log Level
          defaultValue: 'info'
          description: Rails logging level (debug, info, warn, error, fatal)
          validRegex: /^(debug|info|warn|error|fatal)$/
        - id: $$cap_rails_serve_static_files
          label: Serve Static Files
          defaultValue: 'true'
          description: Whether Rails should serve static files (true/false)
          validRegex: /^(true|false)$/

services:
    $$cap_appname:
        image: $$cap_solidus_image
        restart: always
        environment:
            RAILS_ENV: $$cap_rails_env
            RAILS_DEVELOPMENT_HOSTS: '.$$cap_root_domain,$$cap_appname.$$cap_root_domain'
            SECRET_KEY_BASE: $$cap_secret_key_base
            ADMIN_EMAIL: $$cap_admin_email
            ADMIN_PASSWORD: $$cap_admin_password
            RAILS_LOG_LEVEL: $$cap_rails_log_level
            RAILS_SERVE_STATIC_FILES: $$cap_rails_serve_static_files
        caproverExtra:
            containerHttpPort: '3000'
            websocketSupport: 'true'
        volumes:
            - $$cap_appname-data:/rails/public/system
            - $$cap_appname-storage:/rails/storage
